---
title: "What exactly is a 'white paper'?"
author: 
- Eric Koski, Orebed Analytics LLC
date: "`r format(Sys.time(), '%B %d, %Y')`[^0]"
output:
  rmdformats::readthedown:   
    # https://github.com/juba/rmdformats
    number_sections: no
    toc: 2
    highlight: tango
  bookdown::pdf_document2: 
    highlight: tango
    latex_engine: lualatex   # xelatex or lualatex
    keep_tex: yes
    keep_md: yes
    toc: no
    number_sections: no
    citation_package: biblatex      # natbib not tested
    extra_dependencies: 
      flafter: null
      csquotes: null
    includes:
      in_header: preamble.tex
      before_body: before_body.tex
      after_body: 
    # hyperrefoptions: null # pandoc ignores these anyway; see before_body.tex
  bookdown::html_document2:
    df_print: paged
    theme: spacelab
    highlight: tango
    css: custom.css
    number_sections: no
    toc: no
    includes:
      in_header: 
      before_body: 
      after_body: 
mainfont: texgyrepagella-regular.otf
mainfontoptions: "BoldFont=texgyrepagella-bold.otf,
  ItalicFont=texgyrepagella-italic.otf,
  BoldItalicFont=texgyrepagella-bolditalic.otf"
mathfont: texgyrepagella-math.otf
sansfont: zhv.otf                 # Helvetica
monofont: inconsolata.otf
# colorlinks: specify in before_body.tex
colorlinks: true
papersize: letter
geometry: margin=2.54cm   # change if A4
lang: en-US
fontsize: 10pt
bibliography: "white-paper.bib"
biblio-style: alphabetic  # choices include ieee, acm, apa, mls, alphabetic, authoryear, etc.
biblio-title: References
biblatexoptions: 
- hyperref=true
- backref=true
keywords: this, that
abstract: "This is the abstract."
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE)

docType <- "informal report"
```

```{r setup, include=FALSE, message=FALSE}
# setup.R contains library() calls for many useful packages and the functions 
# to make git commit info available to annotate documents. 
source("setup.R")

# A LaTeX way to accomplish the git-stamping which is no longer needed: 
# \blfootnote{\textbf{Current version:} `r format(Sys.time(), '%B %d, %Y')`; 
# \textbf{commit:} `r gitStatusBrief`}
```

[^0]: **Current version:** `r format(Sys.time(), '%B %d, %Y')`; **commit:** `r gitStatusBrief`

## Introduction {#introduction}

Code chunk is included here to verify that syntax highlighting is as expected. 

```{r more_setup, echo=TRUE, message=FALSE}
# utils.R contains misc useful functions; conversions.R includes unit conversions 
# and defines adjustForInflation(dollarValue, fromYear, toYear); additionally, 
# it downloads the annual inflation index from FRED. 
source("utils.R")
source("conversions.R")
```

A biblatex reference: [@nyserdaNewYorkState2019].

A url: https://www.ipums.org/projects/ipums-usa. 

See [Introduction](#introduction).^[This is a footnote.]

Reference to a Pandoc-style footnote.[^a]

[^a]: A Pandoc-style footnote.

\clearpage

```{=html}
<h2>References</h2>
```
